#!/usr/bin/python3

#Even Fibonacci numbers

#Each new term in the Fibonacci sequence is generated by adding the 
#previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not
#exceed four million, find the sum of the even-valued terms.

answer = 0
value = [1,1]
while 4000000 > value[0]:
	if value[0] % 2 == 0:
		answer += value[0]
	value[0], value[1] = value[1], value[0] + value[1]
print(answer)
